### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by eliottmusk** [emvaized/text-reflow-on-zoom-mobile#1]
I tried in the last Firefox for Android, and has any affect.

**Comment by emvaized** [comment]
Hi there! 
Maybe it doesn't support pages which you have tested it on? Could you share urls of these pages? 

For example, here on the page of this issue ticket it works quite well, in both Firefox Stable and Firefox Beta.

**Comment by eliottmusk** [comment]
Here don't work in any site, including on Github, maybe a conflict with some setting? I even disabled uBlock to test, but without success.

**Comment by emvaized** [comment]
Please verify that extension has permission to access all websites:

![Screenshot_20241109_164340_Firefox](https://github.com/user-attachments/assets/29e1591a-c531-4fd5-90bf-cd4545143507)

**Comment by eliottmusk** [comment]
The issue was it, I don't know why the permission was not allowed. Thank you so much!

**Comment by emvaized** [comment]
I'm glad that we got it working!🚀
